### ISSUE TITLE
workingDirectory 能否支持相对路径？

### ISSUE THREAD

**Issue by jzp820927** [HeddaZ/ServiceOnset#5]
我试了一下，workingDirectory 参数好像不支持相对路径，能否考虑添加以 ServiceOnset.exe 或者 ServiceOnset.exe.json 为根的相对路径支持，因为我的cow是放在ServiceOnset目录下面一个子目录。如果我要换电脑，或者移动了ServiceOnset目录到其他位置，又得改workingDirectory 参数，如果使用相对路径的话，只要保持ServiceOnset目录内部结构不变，就不存在这个问题了。

**Comment by HeddaZ** [comment]
感谢你使用本工具，你的提议很酷。
我会尽快做一个小升级。

**Comment by HeddaZ** [comment]
Get the new package from: https://github.com/HeddaZ/ServiceOnset/releases/tag/R1.4

**Comment by jzp820927** [comment]
等这个更新很久了，谢谢作者更新！
