### ISSUE TITLE
再提一个服务管理的建议

### ISSUE THREAD

**Issue by jzp820927** [HeddaZ/ServiceOnset#6]
目前的做法是生成一个 ServiceOnset 服务管理所有程序。如果我用一个ServiceOnset.exe同时管理几个CMD程序，例如像下面这样的配置：
{
	"enableLog": true,
	"services": [
		{
			"name": "aaa",
			"command": "aaa.exe"
		},
		{
			"name": "bbb",
			"command": "bbb.exe"
		},
		{
			"name": "ccc",
			"command": "ccc.exe"
		}
	]
}
如果现在 aaa应用有点小问题，我想重启一下aaa服务，就要重启ServiceOnset服务，这时ServiceOnset管理的 aaa,bbb,ccc,3个程序都会重启，感觉有点不太方便，能不能考虑把不同的程序生成不同的服务，这样可以单独管理，互不影响。比如aaa程序，根据他的 name 值，生成 aaa服务，bbb，ccc，同理。不知我的建议是否合理？

**Comment by HeddaZ** [comment]
感谢你的建议，你的想法很有应用场景；不过我其实也有相对的考量。
目前 ServiceOnset 统一管理的思路也是与市面上已有的 nssm 工具最大的区别所在；
nssm 就是为每个 cmd 创建了不同的服务可以分开重启，但如果服务很多，最后面临的问题是 windows 服务管理器里自定义的和非自定义的混杂在一起难以统一维护和识别，特别再有病毒伪服务混进来就更多了。
所以，ServiceOnset 本身设计的出发点就是轻量、简洁，易来易走。
因此你的这个需求，至少在目前阶段不会考虑加入。感谢你使用本工具~
--------------------------------------------------
其实你的需求可以有一个替代方案：
如果目前你都是使用的 Daemon 或 Interval 模式，那么在需要重启某个 cmd 的时候，只要放心的到进程管理器中直接杀掉它，几分钟后随后它还是自动会被 ServiceOnset 运行起来的。
【注意】Launch 模式是不行的。
